# DSCI 525 - Web and Cloud Computing

Milestone 2: Your team is planning to migrate to the cloud. AWS gave 400$ (100$ each) to your team to support this. As part of this initiative, your team needs to set up a server in the cloud, a collaborative environment for your team, and later move your data to the cloud. After that, your team can wrangle the data in preparation for machine learning.

## Milestone 2 checklist  
You will have mainly 2 tasks. Here is the checklist...
- Task 1: To set up a collaborative environment 
    - Setup your EC2 instance with JupyterHub.
    - Install all necessary things needed in your UNIX server (Amazon EC2 instance).
    - Set up your S3 bucket.
    - Move the data that you wrangled in your last milestone to S3.
- Task 2: Wrangle the data in preparation for machine learning
    - Get the data from S3 in your notebook and make data ready for machine learning.

> Everything in this milestone is to be completed in sequential order. But if you want to divide the tasks, you can ask a team member to work on Task 2 (```4. Get the data that we wrangled in our first milestone.``` and ```6. Wrangle the data in preparation for machine learning```) locally on their laptop while the other members set up the infrastructure (EC2, S3) and TLJH in the cloud. This way, you can move quick.

_***Outside of Milestone:*** I strongly recommend you spin up your own instance and experiment with the s3 bucket in doing something (there are many things that we learned and practical work from video series) to get comfortable with AWS. But we won't be looking at it for a grading purpose._

**Keep in mind:**

- _All services you use are in region ```us-west-2```._

- _Don't store anything in these servers or storage that represents your identity as a student (like your student ID number) ._

- _Use only default VPC and subnet._
    
- _No IP addresses are visible when you provide the screenshot._

- _You do proper budgeting so that you don't run out of credits._ 

- _We want one single notebook for grading, and it's up to your discretion on how you do it. ***So only one person in your group needs to spin up instance and a ```t2.large``` is of decent size.***_

- _Please stop the instance when not in use. This can save you some bucks, but it's again up to you and how you budget your money. Maybe stop it if you or your team won't use it for the next 5 hours?_

- _Your AWS lab will shut down after 4 hours (also your services). When you start it again (after it is stopped), your AWS credentials (***access key***,***secret***, and ***session token***) will change, and you want to update your credentials file with the new one._

- _If you don't want your lab to shut down, click on the start lab again before 4 hours ends. This will fill up your time to 4 hours._

- _Say something went wrong and you want to spin up another EC2 instance, then it will be good to terminate the previous one._

- _We will be choosing the storage to be ```Delete on Termination``` ( that is the default option), which means that stored data in your instance will be lost upon termination. Make sure you save any data to S3 and download the notebooks to your laptop so that next time you have your jupyterHub in a different instance, you can upload your notebook there._

- _Wherever I ask for screenshots, you can provide the screenshot location in your GitHub._

***NOTE:*** Everything you want for this notebook is discussed in lecture 3 and lecture 4. So you can follow the same order of things shown in lecture 4. You can also refer to the videos linked in each section under image ![YouTube](https://cdn.emojidex.com/emoji/hdpi/YouTube.png "YouTube") to see a demo on how to do it. In addition, I will put a link to the lecture note section that applies to each question in this milestone so that you don't get lost.

### 1. Setup your EC2 instance
- Name of the instance to be `mds-your_groupnumber`. For example if my group is 14 I would name it `mds-14`.
- AMI to be `Ubuntu server 22.04 LTS (HVM)`.
- Instance type to be `t2.large`.
- Architecture to be `64-bit(x86)`.
- Storage to be `30 GB`.
- Make sure you install TLJH in your instance, by giving instructions in `User Data`.

> Check [this](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture4.html#setting-up-an-ec2-instance) section in lecture notes for more details on setting up EC2 instance with TLJH.

rubric={correctness:20}

#### Please provide here the GitHub path to your screenshot for grading. Example screenshot below;

<img src="img/01_EC2_instance.png" style='width:100%;'>

https://github.com/UBC-MDS/DSCI525_Group12/blob/main/milestone2/img/01_EC2_instance.png

### 2. Setup the server 

rubric={correctness:20}

2.1) Add your team members to EC2 instance.

2.2) Setup a common data folder to download data, and this folder should be accessible by all users in the JupyterHub.
    
2.3) Install and configure AWS CLI.

> Check following sections in lecture notes for more details;

- [Logging into EC2s](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture4.html#logging-into-ec2)
- [Setting up a common space in EC2](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture4.html#setting-up-a-common-space-in-ec2) 
- [AWS CLI](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture3.html#aws-cli)

#### Please provide here the GitHub path to your screenshot for grading. Example screenshot below;

Make sure you mask the IP address refer [here](https://www.anysoftwaretools.com/blur-part-picture-mac/).

<img src="img/02_Server_setup.png" style='width:100%;'>

https://github.com/UBC-MDS/DSCI525_Group12/blob/main/milestone2/img/02_Server_setup.png

### 3. Setup your JupyterHub

rubric={correctness:20}

#### Please provide here the GitHub path to your screenshot for grading. Example screenshot below;

I want to see all the group members here in this screenshot 

<img src="img/03_Jupyter_Hub_setup.png" style='width:100%;'>

https://github.com/UBC-MDS/DSCI525_Group12/blob/main/milestone2/img/03_Jupyter_Hub_setup.png

<br></br>
> Check [this](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture4.html#setup-your-jupyterhub) section in lecture notes for more details on setting up jupyterHub.

### 4. Get the data what we wrangled in our first milestone.

You have to install the packages that are needed. Refer this TLJH [document]( https://tljh.jupyter.org/en/latest/howto/env/user-environment.html).Refer ```pip``` section.

Don't forget to add option -E. This way, all packages that you install will be available to other users in your JupyterHub.
These packages you must install and install other packages needed for your wrangling.

    sudo -E pip install pandas
    sudo -E pip install pyarrow
    sudo -E pip install s3fs

> Check [this](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture4.html#how-to-install-packages-in-tljh) section in lecture notes for more details on installing packages in TLJH.

As in the last milestone, we looked at transferring the data from Python to R, and we have different solutions. To stay consistent, I uploaded the parquet file (which I combined and converted in the last milestone), which we can use moving forward. Here in this section, I am getting that file using API; (the section is prepopulated for you)

Remember, from now on, we are going to run this notebook in the TLJH that is set up from previous steps. You can upload your notebook there using the upload button in jupyter. After that, you are going to run the following code to get the data downloaded to your EC2 instance and then you move to questions 5 and 6.

In [1]:
import re
import os
import glob
import zipfile
import requests
from urllib.request import urlretrieve
import json
import pandas as pd

Rememeber here we gave the folder that we created in Step 2.2 as we made it available for all the users in a group.

In [6]:
# Necessary metadata
article_id = 14226968  # this is the unique identifier of the article on figshare
url = f"https://api.figshare.com/v2/articles/{article_id}"
headers = {"Content-Type": "application/json"}
output_directory = "/srv/data/group12-ms2-data/"

In [7]:
response = requests.request("GET", url, headers=headers)
data = json.loads(response.text)  # this contains all the articles data, feel free to check it out
files = data["files"]             # this is just the data about the files, which is what we want
files

[{'id': 26844650,
  'name': 'allyears.csv.zip',
  'size': 2405908113,
  'is_link_only': False,
  'download_url': 'https://ndownloader.figshare.com/files/26844650',
  'supplied_md5': '9e046ac05ecd2c32a256a47dd1098b81',
  'computed_md5': '9e046ac05ecd2c32a256a47dd1098b81'},
 {'id': 26863682,
  'name': 'individual_years.zip',
  'size': 1896206676,
  'is_link_only': False,
  'download_url': 'https://ndownloader.figshare.com/files/26863682',
  'supplied_md5': '921da748974b07b2a70bbfcc04535a77',
  'computed_md5': '921da748974b07b2a70bbfcc04535a77'},
 {'id': 27515426,
  'name': 'combined_model_data.csv.zip',
  'size': 821308997,
  'is_link_only': False,
  'download_url': 'https://ndownloader.figshare.com/files/27515426',
  'supplied_md5': '7638434c44a7d29cbb29fe200b4fd65d',
  'computed_md5': '7638434c44a7d29cbb29fe200b4fd65d'},
 {'id': 27520682,
  'name': 'combined_model_data_parti.parquet.zip',
  'size': 519743915,
  'is_link_only': False,
  'download_url': 'https://ndownloader.figshare.com/files/27520682',
  'supplied_md5': '02f4e3df8d16580a02291de225072689',
  'computed_md5': '02f4e3df8d16580a02291de225072689'},
 {'id': 27520808,
  'name': 'combined_model_data.parquet',
  'size': 565872005,
  'is_link_only': False,
  'download_url': 'https://ndownloader.figshare.com/files/27520808',
  'supplied_md5': 'ae63699ab21ffa8006559c6afbcd2271',
  'computed_md5': 'ae63699ab21ffa8006559c6afbcd2271'}]

In [8]:
files_to_dl = ["combined_model_data_parti.parquet.zip"]  ## Please download the partitioned 
for file in files:
    if file["name"] in files_to_dl:
        os.makedirs(output_directory, exist_ok=True)
        urlretrieve(file["download_url"], output_directory + file["name"])

In [9]:
with zipfile.ZipFile(os.path.join(output_directory, "combined_model_data_parti.parquet.zip"), 'r') as f:
    f.extractall(output_directory)

### 5. Setup your S3 bucket and move data

rubric={correctness:15}

> Check [this](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture4.html#setting-up-s3-bucket) section in lecture notes for more details on setting up S3 bucket and ***making it public***. 

5.1)  Create a bucket and name should be mds-s3-groupnumber-studentname. Replace groupnumber with your "group number", and studentname with your "student name". For example, if my group is 14 and my name is "Gittu George", then I would name it "mds-s3-14-gittu". (Note: For the purpose of this milestone only one student need to create this.)

5.2)  Create your first folder called "output".

5.3) Move the "observed_daily_rainfall_SYD.csv" file from the Milestone1 data folder to your s3 bucket from your local computer.

5.4) Moving the parquet file we downloaded(combined_model_data_parti.parquet) in step 4 to S3 using the cli what we installed in step 2.3.


> Check [this](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture4.html#how-to-transfer-data-to-s3) section in lecture notes for more details on moving data to S3.

#### Please provide here the GitHub path to your screenshot for grading. Example screenshot below;

Make sure it has 3 objects and see red `public` symbol in your bucket. Refer below screenshot for reference.

<img src="img/04_S3_bucket.png" style='width:100%;'>

https://github.com/UBC-MDS/DSCI525_Group12/blob/main/milestone2/img/04_S3_bucket.png

### 6. Wrangle the data in preparation for machine learning

rubric={correctness:20}

> ***IMPORTANT:*** Don't forget to deal with the credentials before you start this section. Check details in lecture notes [here](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture4.html#more-about-credentials)

> Check [this](https://pages.github.ubc.ca/MDS-2022-23/DSCI_525_web-cloud-comp_students/lectures/lecture4.html#how-to-read-data-from-s3) section in lecture notes for more details on how to read data from S3.

Our data currently covers all of NSW, but say that our client wants us to create a machine learning model to predict rainfall over Sydney only. There's a bit of wrangling that needs to be done for that:
1. We need to query our data for only the rows that contain information covering Sydney
2. We need to wrangle our data into a format suitable for training a machine learning model. That will require pivoting, resampling, grouping, etc.

To train an ML algorithm we need it to look like this:

||model-1_rainfall|model-2_rainfall|model-3_rainfall|...|observed_rainfall|
|---|---|---|---|---|---|
|0|0.12|0.43|0.35|...|0.31|
|1|1.22|0.91|1.68|...|1.34|
|2|0.68|0.29|0.41|...|0.57|

6.1) Get the data from s3 (```combined_model_data_parti.parquet``` and ```observed_daily_rainfall_SYD.csv```)

6.2) First query for Sydney data and then drop the lat and lon columns (we don't need them).
```
syd_lat = -33.86
syd_lon = 151.21
```
Expected shape ```(1150049, 2)```.

6.3) Save this processed file to s3 for later use:

  Save as a csv file ```ml_data_SYD.csv``` to ```s3://mds-s3-xxx/output/```
  expected shape ```(46020,26)``` - This includes all the models as columns and also adding additional column ```Observed``` loaded from ```observed_daily_rainfall_SYD.csv``` from s3.

In [2]:
os.environ["AWS_SHARED_CREDENTIALS_FILE"] = "/srv/keys/credentials"

In [3]:
import s3fs
import urllib.parse

In [4]:
syd_lat = -33.86
syd_lon = 151.21

In [22]:
# aws_credentials ={"key": "paste_key","secret": "paste_secret","token":"paste_token"} 
rainfall_df = pd.read_parquet('s3://mds-s3-12-cevj/combined_model_data_parti.parquet', 
                              filters=[('lat_min','<', syd_lat), 
                                       ('lat_max','>', syd_lat),
                                       ('lon_min','<', syd_lon), 
                                       ('lon_max','>', syd_lon)],
                              columns=['time', 'rain (mm/day)', 'model'])

rainfall_df['time'] = pd.to_datetime(rainfall_df['time']).dt.date
rainfall_df = rainfall_df.set_index('time')
rainfall_df.head(10)

            rain (mm/day)       model
time
1889-01-01       0.040427  ACCESS-CM2
1889-01-02       0.073777  ACCESS-CM2
1889-01-03       0.232656  ACCESS-CM2
1889-01-04       0.911319  ACCESS-CM2
1889-01-05       0.698013  ACCESS-CM2
1889-01-06       0.176846  ACCESS-CM2
1889-01-07       0.347102  ACCESS-CM2
1889-01-08       0.042755  ACCESS-CM2
1889-01-09       0.029409  ACCESS-CM2
1889-01-10       0.023641  ACCESS-CM2

In [23]:
rainfall_df.shape

(1150049, 2)

In [24]:
rainfall_df = rainfall_df.pivot_table(index='time', 
                                      columns='model', 
                                      values='rain (mm/day)')
rainfall_df.head(10)

model,ACCESS-CM2,ACCESS-ESM1-5,AWI-ESM-1-1-LR,BCC-CSM2-MR,BCC-ESM1,CMCC-CM2-HR4,CMCC-CM2-SR5,CMCC-ESM2,CanESM5,EC-Earth3-Veg-LR,...,MIROC6,MPI-ESM-1-2-HAM,MPI-ESM1-2-HR,MPI-ESM1-2-LR,MRI-ESM2-0,NESM3,NorESM2-LM,NorESM2-MM,SAM0-UNICON,TaiESM1
time,,,,,,,,,,,,,,,,,,,,,
1889-01-01,0.040427,1.814552,35.579336,4.268112e+00,1.107466e-03,11.410537,3.322009e-08,2.668800,1.321215,1.515293e+00,...,0.648031,4.244226e-13,1.390174e-13,6.537884e-05,3.445495e-06,1.576096e+01,4.759651e-05,2.451075,0.221324,2.257933
1889-01-02,0.073777,0.303965,4.596520,1.190141e+00,1.015323e-04,4.014984,1.312700e+00,0.946211,2.788724,4.771375e+00,...,1.099883,4.409552e+00,1.222283e-01,1.049131e-13,4.791993e-09,3.675510e-01,4.350863e-01,0.477231,3.757179,2.287381
1889-01-03,0.232656,0.019976,5.927467,1.003845e-09,1.760345e-05,9.660565,9.103720e+00,0.431999,0.003672,4.233980e+00,...,3.931751,2.269300e-01,3.762301e-01,9.758706e-14,6.912302e-01,1.562869e-01,9.561101e+00,0.023083,0.253357,1.199909
1889-01-04,0.911319,13.623777,8.029624,8.225225e-02,1.808932e-01,3.951528,1.317160e+01,0.368693,0.013578,1.525249e+01,...,0.627365,2.344586e-02,4.214019e-01,7.060915e-03,3.835721e-02,2.472226e-07,5.301038e-01,0.002699,2.185454,2.106737
1889-01-05,0.698013,0.021048,2.132686,2.496841e+00,4.708019e-09,2.766362,1.822940e+01,0.339267,0.002468,1.192036e+01,...,0.019777,4.270161e-13,1.879692e-01,4.504985e+00,3.506923e-07,1.949792e-13,1.460928e-10,0.001026,2.766507,1.763335
1889-01-06,0.176846,0.364671,0.106105,4.383307e-13,3.437249e-07,23.617552,4.036332e+00,0.008937,0.000000,7.534027e-02,...,0.490276,3.888130e-01,1.212115e-13,4.027802e+00,8.058601e-01,1.926850e-13,1.192076e-03,2.155050,3.281224,0.096504
1889-01-07,0.347102,0.012561,0.780772,4.599509e-04,1.598180e+01,9.254538,5.343101e+00,15.105793,0.211540,3.154230e+00,...,35.833649,2.101678e-02,1.187939e-13,2.491990e-01,8.221049e-13,1.490119e-01,6.488937e-01,6.970733,1.117913,3.021798
1889-01-08,0.042755,0.087271,0.312471,1.182123e-06,8.529780e+00,17.310366,7.936454e+00,36.009891,0.013135,2.109385e+00,...,2.013104,2.094235e-01,1.931241e-01,9.888659e-14,1.766779e-03,8.325429e+00,4.708920e-01,0.858247,53.212309,2.886699
1889-01-09,0.029409,0.367011,0.698855,1.814032e+00,1.793289e-01,21.376961,2.659956e+00,2.105408,23.622214,-3.911231e-20,...,0.028268,4.433096e-13,2.564862e-03,4.506111e+00,5.282789e+00,1.833132e-13,4.403384e-03,3.504712,0.583404,2.902378
1889-01-10,0.023641,1.204603,0.855432,2.041867e-08,4.213335e-01,2.649612,8.852351e-01,0.548089,0.394165,6.866455e-02,...,0.522575,5.243283e-01,2.156345e-01,1.909716e+01,6.569285e-04,1.059172e-06,1.241138e-01,15.477286,0.059971,0.315518

In [25]:
rainfall_df.shape

(46020, 25)

In [26]:
# Load observed data and add to the rainfall_df
rainfall_df_observed = pd.read_csv('s3://mds-s3-12-cevj/observed_daily_rainfall_SYD.csv')
rainfall_df_observed['time'] = pd.to_datetime(rainfall_df_observed['time']).dt.date
rainfall_df_observed = rainfall_df_observed.set_index('time')
rainfall_df_observed.head(10)

            rain (mm/day)
time
1889-01-01       0.006612
1889-01-02       0.090422
1889-01-03       1.401452
1889-01-04      14.869798
1889-01-05       0.467628
1889-01-06       0.000000
1889-01-07       0.403645
1889-01-08       0.111741
1889-01-09       0.000000
1889-01-10       0.000000

In [27]:
rainfall_df['observed'] = rainfall_df_observed['rain (mm/day)']
rainfall_df.shape

(46020, 26)

How the final file format looks like
<img src="image/finaloutput.png" >

Shape ```(46020,26 )```

In [28]:
# Save dateframe to output folder on S3
rainfall_df.to_csv('s3://mds-s3-12-cevj/output/ml_data_SYD.csv')

<br><br>
## Submission instructions
rubric={mechanics:5}

In the textbox provided on Canvas for the Milestone 2 assignment include:

- The GitHub URL to your Milestone 2 folder.

In this milestone 2 folder, you should have this notebook and screenshots asked in this notebook.